name: Run PHPStan

# Run PHPStan to annotate the code

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, synchronize]

jobs:
  phpstan:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [ '8.0' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Install PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          tools: composer, cs2pr
          extensions: zip

      - name: Install sponge
        run: sudo apt-get install moreutils

      - name: Run composer install
        run: composer install

      - name: Run PHPStan at max level to add annotations to the code
        id: phpstan_max
        continue-on-error: true
        run: |
          vendor/bin/phpstan analyse -c phpstan.neon --level max --memory-limit 1G --error-format=checkstyle | cs2pr

      # On merge to main, fail for any error in `includes`.
      - name: Run PHPStan to print errors on the includes directory in the normal format and fail hard (main)
        run: vendor/bin/phpstan analyse includes -c phpstan.neon --memory-limit 1G
        if: ${{ github.event_name != 'pull_request' }}

      - name: Get changed files
        if: ${{ github.event_name == 'pull_request' }}
        id: changed_files_includes
        uses: tj-actions/changed-files@v47
        with:
          separator: ' '
          files: 'includes/**/**.php'

      # This outputs `steps.pr_diff.outputs.diff_filename` and `steps.pr_diff.outputs.diff_contents`.
      - name: Get the PR diff
        id: pr_diff
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          FILENAME="${{ env.TARGET_BRANCH_REF_NAME }}-${{ github.event.pull_request.head.sha }}.diff"
          git fetch origin ${{ env.TARGET_BRANCH_REF_NAME }}:refs/remotes/origin/${{ env.TARGET_BRANCH_REF_NAME }}
          git diff origin/${{ env.TARGET_BRANCH_REF_NAME }} > tmp.diff
          mv tmp.diff $FILENAME
          echo "diff_filename=$FILENAME" >> $GITHUB_OUTPUT
          EOF=$(dd if=/dev/urandom bs=15 count=1 status=none | base64)
          echo "diff_contents<<$EOF" >> $GITHUB_OUTPUT
          echo "$(cat $FILENAME)" >> $GITHUB_OUTPUT
          echo "$EOF" >> $GITHUB_OUTPUT
        env:
          TARGET_BRANCH_REF_NAME: ${{ github.event.pull_request.base.ref }}

      # On PRs, only fail for errors in important modified files.
      - name: Run PHPStan at phpstan.neon level only on changed_files in includes directory
        if: ${{ github.event_name == 'pull_request' }}
        continue-on-error: true
        run: vendor/bin/phpstan analyse ${{ steps.changed_files_includes.outputs.all_changed_files }} -c phpstan.neon --memory-limit 1G --error-format=checkstyle | sponge phpstan-checkstyle.xml

      - name: Fail if there are still phpcs errors in the modified files (pr)
        if: ${{ github.event_name == 'pull_request' }}
        run: |
          vendor/bin/prf filter-checkstyle ${{ env.DIFF_FILENAME }} ${{ env.CHECKSTYLE_FILENAME }}  filtered-checkstyle.xml --base-path=$(pwd)
          cat filtered-checkstyle.xml | cs2pr
        env:
          DIFF_FILENAME: ${{ steps.pr_diff.outputs.diff_filename }}
          CHECKSTYLE_FILENAME: "phpstan-checkstyle.xml"
